name: ci
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Lerna Bootstrap
        run: npx lerna bootstrap

      - name: Check Circular Dependencies
        run: npm run madge

      - name: Build
        run: npm run build

      # - name: Lint
      #   run: npm run lint

      - name: Test
        run: npm run test

      - name: Playable Tests Setup
        run: npm ci && npx lerna link
        working-directory: ./spec/

      - name: Playable Tests
        run: npm start
        working-directory: ./spec/
      
      - name: Upload Logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./spec/logs/
        if: success() || failure()